# Generated by Django 5.1.1 on 2024-09-24 07:15

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='keywords',
        ),
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.CharField(choices=[('index', 'Index Page'), ('about', 'About Page'), ('services', 'Services Page'), ('register', 'Register Page'), ('reports', 'Reports Page'), ('cs', 'CS Page'), ('ml', 'ML Page'), ('economics', 'Economics Page'), ('data_analysis', 'Data Analysis Page'), ('data_mining', 'Data Mining Page'), ('finance', 'Finance Page'), ('business_analytics', 'Business Analytics Page'), ('case_studies', 'Case Studies Page'), ('business', 'Business Page'), ('marketing', 'Marketing Page'), ('research', 'Research Page')], default='index', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[core.validators.validate_file_size, core.validators.validate_file_type]),
        ),
    ]
