# Generated by Django 5.1.1 on 2025-04-28 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_document_file_type_remove_document_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_count", models.IntegerField(default=0)),
                ("avg_load_time", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="document",
            name="page",
            field=models.CharField(
                choices=[
                    ("index", "Index Page"),
                    ("about", "About Page"),
                    ("services", "Services Page"),
                    ("register", "Register Page"),
                    ("reports", "Reports Page"),
                    ("cs", "CS Page"),
                    ("ml", "ML Page"),
                    ("economics", "Economics Page"),
                    ("data_analysis", "Data Analysis Page"),
                    ("data_mining", "Data Mining Page"),
                    ("finance", "Finance Page"),
                    ("business_analytics", "Business Analytics Page"),
                    ("case_studies", "Case Studies Page"),
                    ("business", "Business Page"),
                    ("marketing", "Marketing Page"),
                    ("research", "Research Page"),
                    ("past_solutions", "Past Solutions Page"),
                ],
                default="index",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("index", "Index Page"),
                            ("about", "About Page"),
                            ("services", "Services Page"),
                            ("register", "Register Page"),
                            ("reports", "Reports Page"),
                            ("cs", "CS Page"),
                            ("ml", "ML Page"),
                            ("economics", "Economics Page"),
                            ("data_analysis", "Data Analysis Page"),
                            ("data_mining", "Data Mining Page"),
                            ("finance", "Finance Page"),
                            ("business_analytics", "Business Analytics Page"),
                            ("case_studies", "Case Studies Page"),
                            ("business", "Business Page"),
                            ("marketing", "Marketing Page"),
                            ("research", "Research Page"),
                            ("past_solutions", "Past Solutions Page"),
                        ],
                        default="past_solutions",
                        max_length=50,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.user"
                    ),
                ),
            ],
        ),
    ]
