# Generated by Django 5.1.1 on 2025-05-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_question_posted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.document",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="page",
            field=models.CharField(
                choices=[
                    ("index", "Index Page"),
                    ("about", "About Page"),
                    ("services", "Services Page"),
                    ("register", "Register Page"),
                    ("reports", "Reports Page"),
                    ("computer_science", "computer_science Page"),
                    ("machine_learning", "machine_learning Page"),
                    ("economics", "Economics Page"),
                    ("data_analysis", "Data Analysis Page"),
                    ("data_mining", "Data Mining Page"),
                    ("finance", "Finance Page"),
                    ("business_analytics", "Business Analytics Page"),
                    ("case_studies", "Case Studies Page"),
                    ("business", "Business Page"),
                    ("marketing", "Marketing Page"),
                    ("research", "Research Page"),
                    ("past_solutions", "Past Solutions Page"),
                ],
                default="index",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="page",
            field=models.CharField(
                choices=[
                    ("index", "Index Page"),
                    ("about", "About Page"),
                    ("services", "Services Page"),
                    ("register", "Register Page"),
                    ("reports", "Reports Page"),
                    ("computer_science", "computer_science Page"),
                    ("machine_learning", "machine_learning Page"),
                    ("economics", "Economics Page"),
                    ("data_analysis", "Data Analysis Page"),
                    ("data_mining", "Data Mining Page"),
                    ("finance", "Finance Page"),
                    ("business_analytics", "Business Analytics Page"),
                    ("case_studies", "Case Studies Page"),
                    ("business", "Business Page"),
                    ("marketing", "Marketing Page"),
                    ("research", "Research Page"),
                    ("past_solutions", "Past Solutions Page"),
                ],
                default="past_solutions",
                max_length=50,
            ),
        ),
    ]
